export const GET_CINEMAS = 'GET_CINEMAS'
export const GET_CINEMAS_SUCCESS = 'GET_CINEMAS_SUCCESS'
export const GET_CINEMAS_FAIL = 'GET_CINEMAS_FAIL'


export const GET_MOVIES = 'GET_MOVIES'
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS'
export const GET_MOVIES_FAIL = 'GET_MOVIES_FAIL'

export const GET_UPCOMING = 'GET_UPCOMING'
export const GET_UPCOMING_SUCCESS = 'GET_UPCOMING_SUCCESS'
export const GET_UPCOMING_FAIL = 'GET_UPCOMING_FAIL'